### ISSUE TITLE
Refresh task status

### ISSUE THREAD

**Issue by sduenas** [Bitergia/raistlin#24]
Tasks list view and task view doesn't refresh the status of a task. The user has to to it manually.
The goal of this task is to add an autorefresh so the views are constantly updated to show the current status.

**Comment by dlumbrer** [comment]
First step: check how is the best way to do it (thinking on websockets), some links to take a look:

- https://channels.readthedocs.io/en/latest/ - Django channels
- https://ws4py.readthedocs.io/en/latest/sources/ws4py.server/?highlight=cherry#module-ws4py.server.cherrypyserver - CherryPy websockets

**Comment by dlumbrer** [comment]
I prepared a PR in order to check if the solution is valid or no, please @sduenas check it when you have time.

Basically I followed the official doc for django channels [1] and I adapted it to our case, adding the consumers, the URL and the corresponding connection to the ui part:

![Peek 2019-12-10 18-28](https://user-images.githubusercontent.com/9249232/70553384-4b829d80-1b7b-11ea-8f6a-096f99052cc6.gif)

[1]: https://channels.readthedocs.io/en/latest/tutorial/part_2.html

**Comment by dlumbrer** [comment]
I updated the PR (#28), including the functionality of refreshing the task in the Task view, completing all the functionality of the Task refresh. Here is a demo of it:

![Peek 2019-12-11 12-20](https://user-images.githubusercontent.com/9249232/70617338-aa462680-1c10-11ea-83ec-6f6cb0b7c0f4.gif)


Take a look when you have time @sduenas

**Comment by dlumbrer** [comment]
PR closed: https://github.com/Bitergia/raistlin/pull/28#issuecomment-566014171


---

The next step is to add the refresh in the UI that will call the Django server X seg, with these conditions:

- When the user is in the task view, only refresh it if the task is not COMPLETED or FAILED.
- When the user is in the task list view, refresh all the data independently of the task status.

**Comment by dlumbrer** [comment]
A PR has been submitted with the functionality (#29), please @sduenas check it when you have time.
